### ISSUE TITLE
Reference error for STARTTLS connections

### ISSUE THREAD

**Issue by timelesshaze** [mscdex/node-imap#512]
The following ReferenceError is always thrown in case STARTTLS is used:

ReferenceError: config is not defined
lib/Connection.js:1700
self._sock.setTimeout(config.socketTimeout);

**Comment by timelesshaze** [comment]
Fixed by #513

**Comment by JoshWillik** [comment]
I'm still seeing this error on 0.8.16

**Comment by JoshWillik** [comment]
The code seems to be fixed on [this line](https://github.com/mscdex/node-imap/blob/master/lib/Connection.js#L1709), but the code on NPM is still wrong
